// src/lib/components/EntryForm/TimeEntryForm.svelte
<script>
  import nocodbApi from "$lib/nocodbClient.js";
  import { onMount } from "svelte";
  import { buttonRed, buttonBlue } from "$lib/components/colors.js";
  import AchillButton from "$lib/components/TroiButton.svelte";
  import { validateForm } from "../EntryForm/timeEntryFormValidator";

  export let values = {
    hours: "",
    description: "",
  };
  export let errors = {};

  export let addOrUpdateClicked;
  export let deleteClicked = () => {};
  export let recurringTasks;
  export let phaseTasks;
  export let position;
  export let disabled;
  export let minRows = 4;
  export let maxRows = 40;
  export let addMode = false;
  export let updateMode = false;

  let errorTestId = `error-${position.id}`;
  let hoursTestId = `hours-${position.id}`;
  let descriptionTestId = `description-${position.id}`;

  $: minHeight = `${1 + minRows * 1.2}em`;
  $: maxHeight = maxRows ? `${1 + maxRows * 1.2}em` : `auto`;

  let descriptionSegments =
    values.description !== "" ? values.description.split(", ") : [];
  $: description = descriptionSegments.join(", ");

  const normalAppearance = "border-1 border-b-[1px] border-gray-300 ";
  const errorAppearance =
    "border border-b-2 border-red-500 focus:ring-red-500 focus:border-red-500";

  const inputClass =
    "w-full basis-3/4 rounded px-3 py-2 text-sm placeholder:italic placeholder:text-gray-400 leading-6 ";
  const inputNormalAppearance = inputClass + normalAppearance;
  const inputErrorAppearance = inputClass + errorAppearance;

  const textAreaClass =
    "inherit border-box absolute top-0 h-full w-5/6 overflow-hidden p-[0.5em] leading-4 ";
  const textareaNormalAppearance = textAreaClass + normalAppearance;
  const textareaErrorAppearance = textAreaClass + errorAppearance;

  function onKeyDown(e) {
    if (e.keyCode === 13) {
      addOrUpdateClicked(values.hours, values.description);
    }
  }

  function handleDescriptionChange(event) {
    errors = {};
    description = event.target.value;
    descriptionSegments = event.target.value
      .split(", ")
      .filter((item) => item !== "");
  }

  function onRecurringTaskChange(event) {
    if (event.target.checked) {
      descriptionSegments = [...descriptionSegments, event.target.id];
    } else {
      descriptionSegments = descriptionSegments.filter(
        (segment) => segment !== event.target.id
      );
    }
  }

  function handleChipClick(phaseAndTask) {
    if (!descriptionSegments.includes(phaseAndTask)) {
      descriptionSegments = [...descriptionSegments, phaseAndTask];
    }
  }

  function removeChip(phaseAndTask) {
    descriptionSegments = descriptionSegments.filter(
      (segment) => segment !== phaseAndTask
    );
  }

  async function handleAdd() {
    values.description = description;
    errors = await validateForm(values);
    if (Object.keys(errors).length === 0) {
      addOrUpdateClicked(values.hours, values.description);
      values.hours = "";
      values.description = "";
    }
  }

  async function handleUpdate() {
    values.description = description;
    errors = await validateForm(values);

    if (Object.keys(errors).length === 0) {
      addOrUpdateClicked(values.hours, values.description);
      values.hours = "";
      values.description = "";

      // TODO noci: do like with handleAdd
      setTimeout(() => {
        updateMode = false;
        phases.forEach((phase) => (phase.open = false));
      }, 2000);
    }
  }

  async function pollPhaseNames(positionId, subprojectId) {
    let whereClause = [];
    const phaseIdsForPosition = await nocodbApi.dbViewRow.list(
      "noco",
      "ds4g-data",
      "Tracky-Position-Phase",
      "Tracky-Position-Phase",
      {
        where: `(Position ID,eq,${positionId})`,
      }
    );
    phaseIdsForPosition.list.forEach((phaseId) =>
      whereClause.push(`(Phase ID,eq,${phaseId["Phase ID"]})`)
    );

    const phaseIdsForSubproject = await nocodbApi.dbViewRow.list(
      "noco",
      "ds4g-data",
      "Tracky-Subproject-Phase",
      "Tracky-Subproject-Phase",
      {
        where: `(Subproject ID,eq,${subprojectId})`,
      }
    );
    phaseIdsForSubproject.list.forEach((phaseId) =>
      whereClause.push(`(Phase ID,eq,${phaseId["Phase ID"]})`)
    );

    if (whereClause.length > 0) {
      return nocodbApi.dbViewRow.list(
        "noco",
        "ds4g-data",
        "Tracky-Phase",
        "Tracky-Phase",
        {
          where: whereClause.join("~or"),
        }
      );
    }
  }

  let phases;

  onMount(async () => {
    const phaseNames = await pollPhaseNames(position.id, position.subproject);
    if (phaseNames) {
      phases = phaseNames.list
        .map((phase) => phase["Phase Name"])
        .map((value) => ({ name: value, open: false }));
      openPhases();
    }
  });

  function togglePhase(phase) {
    phase.open = !phase.open;
  }

  function openPhases() {
    for (const phase of phases) {
      for (const phaseTask of phaseTasks) {
        if (
          descriptionSegments.includes([phaseTask.name, phase.name].join(" "))
        ) {
          phase.open = true;
          break;
        }
      }
    }
  }
</script>

<div data-test="entry-form" class="my-2 flex justify-center">
  <div class="block w-full rounded-lg bg-gray-100 p-4 shadow-lg">
    <div class="flex flex-col">
      <div class="basis-3/4 p-1">
        <h2
          class="mb-4 text-lg font-semibold text-gray-900"
          title="Position ID: {position.id}"
          data-testid="project-heading-{position.id}"
        >
          {position.name}
        </h2>
        {#if addMode || updateMode}
          <div id="timeEntryForm">
            <div class="relative flex w-full items-center">
              <div>
                <label for="hours" class="pr-2">Hours</label>
                <input
                  bind:value={values.hours}
                  on:keydown={onKeyDown}
                  type="text"
                  id="hours"
                  data-testid={hoursTestId}
                  class={`${
                    errors.hours ? inputErrorAppearance : inputNormalAppearance
                  } w-3/12`}
                  placeholder="2:15"
                />
              </div>
              <div class="mt-1">
                {#if Object.values(errors).length > 0}
                  <div class="font-bold text-red-600">
                    <ul>
                      {#each Object.values(errors) as error}
                        <li>
                          &#x26A0; {error}
                        </li>
                      {/each}
                    </ul>
                  </div>
                {/if}
              </div>
            </div>
            <div class="my-8">
              {#if recurringTasks && phases}
                <label for="recurring" class="basis-1/4">Recurring tasks</label>
                <div id="recurring" class="mt-2 space-x-1">
                  {#each recurringTasks as entry}
                    <input
                      checked={descriptionSegments.includes(entry.name)}
                      class="rounded-md border border-gray-300 bg-white p-2"
                      id={entry.name}
                      type="checkbox"
                      on:change={onRecurringTaskChange}
                    />
                    <label class="pr-5" for={entry.name}>{entry.name}</label>
                  {/each}
                </div>
              {/if}
            </div>
            <div class="mb-4">
              {#if phases}
                {#each phases as phase}
                  <details class="mb-[20px]" bind:open={phase.open}>
                    <summary
                      class="flex h-12 w-full flex-row items-center gap-4 rounded-t border-b-2 border-solid border-b-[#CED4DA] bg-[#E5E5E5] px-[16px] py-[20px]"
                      on:click={() => togglePhase(phase)}
                    >
                      <span>{phase.name}</span>
                      <svg
                        class="ml-auto h-4 w-4 transform transition-transform {phase.open
                          ? 'rotate-180'
                          : ''}"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          stroke-width="2"
                          d="M19 9l-7 7-7-7"
                        />
                      </svg>
                    </summary>
                    {#if phaseTasks}
                      <div
                        class="flex h-auto flex-wrap border-b-2 border-solid border-b-[#CED4DA] bg-white p-2"
                      >
                        {#each phaseTasks as task}
                          <div
                            class="m-2 flex cursor-pointer items-center rounded-full border py-1 px-3 text-sm transition-all duration-150 ease-in-out {descriptionSegments.includes(
                              [task.name, phase.name].join(' ')
                            )
                              ? 'border-black bg-white'
                              : 'bg-[#212121] bg-opacity-10 hover:bg-gray-300'}"
                            on:click={() =>
                              handleChipClick(
                                [task.name, phase.name].join(" ")
                              )}
                          >
                            <span>{task.name}</span>
                            {#if descriptionSegments.includes([task.name, phase.name].join(" "))}
                              <button
                                class="ml-2 flex h-4 w-4 items-center justify-center rounded-full bg-gray-600 text-white hover:bg-gray-800"
                                on:click={(event) => {
                                  event.stopPropagation();
                                  removeChip([task.name, phase.name].join(" "));
                                }}
                              >
                                &#x2715;
                              </button>
                            {/if}
                          </div>
                        {/each}
                      </div>
                    {/if}
                  </details>
                {/each}
              {/if}
            </div>
            <div class="relative mb-4 flex w-full items-center justify-between">
              <div class="w-4/6">
                <pre
                  aria-hidden="true"
                  class="inherit border-box overflow-hidden p-[0.5em] leading-4"
                  style="min-height: {minHeight}; max-height: {maxHeight}">{description +
                    "\n"}</pre>

                <textarea
                  value={description}
                  on:keydown={onKeyDown}
                  on:input={handleDescriptionChange}
                  id="description"
                  data-testid={descriptionTestId}
                  class={`${
                    errors.description
                      ? textareaErrorAppearance
                      : textareaNormalAppearance
                  }`}
                  placeholder="Working the work…"
                />
              </div>
              <div class="flex flex-col space-y-2">
                {#if !disabled}
                  {#if updateMode}
                    <AchillButton
                      text={"Save"}
                      testId={`update-${position.id}`}
                      onClick={handleUpdate}
                      color={buttonBlue}
                    />
                    <AchillButton
                      text={"Cancel"}
                      testId={`cancel-${position.id}`}
                      onClick={() => {
                        updateMode = false;
                      }}
                      color={buttonRed}
                    />
                  {/if}
                  {#if addMode}
                    <AchillButton
                      text={"Save"}
                      testId={"add-" + position.id}
                      onClick={handleAdd}
                      color={buttonBlue}
                    />
                  {/if}
                {/if}
              </div>
            </div>
          </div>
        {:else}
          <div data-testid="entry-card-content">
            <b>{values.hours} Hour(s)</b><br />
            <p>{values.description}</p>
            <br />
            <AchillButton
              text={"Delete"}
              testId={`delete-${position.id}`}
              onClick={() => {
                deleteClicked();
              }}
              color={buttonRed}
            />
            {#if !disabled}
              <AchillButton
                text={"Edit"}
                testId={`edit-${position.id}`}
                onClick={() => {
                  openPhases();
                  updateMode = true;
                }}
                color={buttonBlue}
              />
            {/if}
          </div>
        {/if}
      </div>
    </div>
  </div>
</div>

// app/components/TimeEntryForm.tsx
import { Project } from "~/troi/troiController";
import { useEffect, useState } from "react";
import { TroiButton } from "./TroiButton";
import { buttonBlue, buttonRed } from "~/utils/colors";
import { TrackyTask } from "~/tasks/useTasks";
import { usePhaseNames } from "~/tasks/usePhaseNames";

interface Props {
  values?: {
    hours: string;
    description: string;
  };
  errors?: {
    hours?: string;
    description?: string;
  };
  addOrUpdateClicked: (hours: string, description: string) => unknown;
  deleteClicked?: () => unknown;
  recurringTasks: TrackyTask[];
  phaseTasks: TrackyTask[];
  position: Project;
  disabled: boolean;
  minRows?: number;
  maxRows?: number;
  addMode?: boolean;
}

function descriptionToSegmenets(description: string): string[] {
  return description !== ""
    ? description
        .split(",")
        .map((segment) => segment.trim())
        .filter((segment) => segment !== "")
    : [];
}

function segmentsToDescription(segments: string[]): string {
  return segments.join(", ");
}

export function TimeEntryForm({
  values = {
    hours: "",
    description: "",
  },
  errors = {},
  addOrUpdateClicked,
  deleteClicked,
  recurringTasks,
  phaseTasks,
  position,
  disabled,
  minRows = 4,
  maxRows = 40,
  addMode = false,
}: Props) {
  const hoursTestId = `hours-${position.id}`;
  const descriptionTestId = `description-${position.id}`;

  const normalAppearance = "border-1 border-b-[1px] border-gray-300 ";
  const errorAppearance =
    "border border-b-2 border-red-500 focus:ring-red-500 focus:border-red-500";

  const inputClass =
    "w-full basis-3/4 rounded px-3 py-2 text-sm placeholder:italic placeholder:text-gray-400 leading-6 ";
  const inputNormalAppearance = inputClass + normalAppearance;
  const inputErrorAppearance = inputClass + errorAppearance;

  const textAreaClass =
    "inherit border-box absolute top-0 overflow-hidden p-[0.5em] leading-4 ";
  const textareaNormalAppearance = textAreaClass + normalAppearance;
  const textareaErrorAppearance = textAreaClass + errorAppearance;

  const minHeight = `${1 + minRows * 1.2}em`;
  const maxHeight = maxRows ? `${1 + maxRows * 1.2}em` : `auto`;

  const [description, setDescription] = useState(() => values.description);

  const descriptionSegments = descriptionToSegmenets(description);
  const [hours, setHours] = useState(values.hours);
  const [updateMode, setUpdateMode] = useState(false);

  const phaseNames = usePhaseNames(position.id, position.subproject);
  const phases = phaseNames.map((value) => {
    for (const phaseTask of phaseTasks) {
      if (descriptionSegments.includes([phaseTask.name, value].join(" "))) {
        return { name: value, open: true };
      }
    }
    return { name: value, open: false };
  });

  function addDescriptionSegment(segment: string) {
    setDescription((description) =>
      segmentsToDescription([...descriptionToSegmenets(description), segment]),
    );
  }

  function removeDescriptionSegment(segment: string) {
    setDescription((description) => {
      const segments = descriptionToSegmenets(description);
      return segmentsToDescription(
        segments.filter((entry) => entry !== segment),
      );
    });
  }

  function toggleDescriptionSegment(segment: string) {
    if (description.includes(segment)) {
      removeDescriptionSegment(segment);
    } else {
      addDescriptionSegment(segment);
    }
  }

  function removeDuplicatedCommas(description: string) {
    const segments = descriptionToSegmenets(description);
    return segmentsToDescription(
      segments.filter(
        (entry, index) => entry !== "" || index === segments.length - 1,
      ),
    );
  }

  function hasDuplicatedCommas(description: string) {
    return description.match(/\,\s*\,/g) !== null;
  }

  function handleDescriptionChange(
    event: React.FormEvent<HTMLTextAreaElement>,
  ) {
    if (
      event.nativeEvent instanceof InputEvent &&
      event.target instanceof HTMLTextAreaElement
    ) {
      if (event.nativeEvent.inputType !== "insertLineBreak") {
        errors = {};
      }
      let newDescription = event.target.value;
      if (hasDuplicatedCommas(newDescription)) {
        newDescription = removeDuplicatedCommas(newDescription);
      }
      setDescription(newDescription);
    } else {
      console.error("handleDescriptionChange", event);
      // todo throw something
    }
  }

  async function onKeyDown(e) {
    if (e.keyCode === 13) {
      /*errors = await validateForm({
        hours: hours,
        description: description,
      });*/
      if (Object.keys(errors).length === 0) {
        addOrUpdateClicked(hours, description);
        setHours("");
        setDescription("");
      }
    }
  }

  async function handleAdd() {
    // errors = await validateForm(values);
    if (Object.keys(errors).length === 0) {
      addOrUpdateClicked(hours, description);
      setHours("");
      setDescription("");
    }
  }

  async function handleUpdate() {
    // errors = await validateForm(values);

    if (Object.keys(errors).length === 0) {
      addOrUpdateClicked(hours, description);
      setHours(hours);
      setDescription(description);
      setUpdateMode(false);
    }
  }

  function handleCancel() {
    setHours(values.hours);
    setDescription(values.description);
    setUpdateMode(false);
  }

  function onRecurringTaskChange(event: React.ChangeEvent<HTMLInputElement>) {
    if (event.target.checked) {
      addDescriptionSegment(event.target.id);
    } else {
      removeDescriptionSegment(event.target.id);
    }
  }

  function handleChipClick(phaseAndTask: string) {
    toggleDescriptionSegment(phaseAndTask);
  }

  function removeChip(phaseAndTask: string) {
    removeDescriptionSegment(phaseAndTask);
  }

  return (
    <div data-test="entry-form" className="my-2 flex justify-center">
      <div className="block w-full rounded-lg bg-gray-100 p-4 shadow-lg">
        <div className="flex flex-col">
          <div className="basis-3/4 p-1">
            <h2
              className="mb-4 text-lg font-semibold text-gray-900"
              title="Position ID: {position.id}"
              data-testid="project-heading-{position.id}"
            >
              {position.name}
            </h2>
            {addMode || updateMode ? (
              <div id="timeEntryForm">
                <div className="relative flex w-full items-center">
                  <div>
                    <label htmlFor="hours" className="pr-2">
                      Hours
                    </label>
                    <input
                      value={hours}
                      onKeyDown={onKeyDown}
                      onChange={(e) => {
                        setHours(e.target.value);
                      }}
                      type="text"
                      id="hours"
                      data-testid={hoursTestId}
                      className={`${
                        errors.hours
                          ? inputErrorAppearance
                          : inputNormalAppearance
                      } w-3/12`}
                      placeholder="2:15"
                    />
                  </div>
                  <div className="mt-1">
                    {Object.values(errors).length > 0 && (
                      <div className="font-bold text-red-600">
                        <ul>
                          {Object.values(errors).map((error) => (
                            <li>&#x26A0; {error}</li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                </div>
                <div className="my-8">
                  {recurringTasks && phases && (
                    <>
                      <label htmlFor="recurring" className="basis-1/4">
                        Recurring tasks
                      </label>
                      <div id="recurring" className="mt-2">
                        {recurringTasks.map((entry) => (
                          <div className="flex items-start space-x-2 md:inline-flex">
                            <input
                              checked={descriptionSegments.includes(entry.name)}
                              className="rounded-md border border-gray-300 bg-white p-2"
                              id={entry.name}
                              type="checkbox"
                              onChange={onRecurringTaskChange}
                            />
                            <label className="pr-5" htmlFor={entry.name}>
                              {entry.name}
                            </label>
                          </div>
                        ))}
                      </div>
                    </>
                  )}
                </div>
                <div className="mb-4">
                  {phases.map((phase) => (
                    <details className="mb-[20px]" open={phase.open}>
                      <summary className="flex w-full flex-row items-center gap-4 rounded-t border-b-2 border-solid border-b-[#CED4DA] bg-[#E5E5E5] px-[16px] py-[20px]">
                        <span>{phase.name}</span>
                        <svg
                          className={`ml-auto h-4 w-4 transform transition-transform ${
                            phase.open ? "rotate-180" : ""
                          }`}
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M19 9l-7 7-7-7"
                          />
                        </svg>
                      </summary>
                      {phaseTasks && (
                        <div className="flex h-auto flex-wrap border-b-2 border-solid border-b-[#CED4DA] bg-white p-2">
                          {phaseTasks.map((task) => (
                            <div
                              className={`m-2 flex cursor-pointer items-center rounded-full border py-1 px-3 text-sm transition-all duration-150 ease-in-out ${
                                descriptionSegments.includes(
                                  [task.name, phase.name].join(" "),
                                )
                                  ? "border-black bg-white"
                                  : "bg-[#212121] bg-opacity-10 hover:bg-gray-300"
                              }`}
                              onClick={() =>
                                handleChipClick(
                                  [task.name, phase.name].join(" "),
                                )
                              }
                            >
                              <span>{task.name}</span>
                              {descriptionSegments.includes(
                                [task.name, phase.name].join(" "),
                              ) && (
                                <button
                                  className="ml-2 flex h-4 w-4 items-center justify-center rounded-full bg-gray-600 text-white hover:bg-gray-800"
                                  onClick={(event) => {
                                    event.stopPropagation();
                                    removeChip(
                                      [task.name, phase.name].join(" "),
                                    );
                                  }}
                                >
                                  &#x2715;
                                </button>
                              )}
                            </div>
                          ))}
                        </div>
                      )}
                    </details>
                  ))}
                </div>
                <div className="relative mb-4 flex w-full flex-col items-center justify-between md:flex-row">
                  <div className="mb-2 w-full md:mb-0 md:w-4/6">
                    <pre
                      aria-hidden="true"
                      className="inherit border-box overflow-hidden p-[0.5em] leading-4"
                      style={{ minHeight, maxHeight }}
                    >
                      {description + "\n"}
                    </pre>

                    <textarea
                      value={description}
                      onKeyDown={onKeyDown}
                      onInput={handleDescriptionChange}
                      id="description"
                      data-testid={descriptionTestId}
                      className={`${
                        errors.description
                          ? textareaErrorAppearance
                          : textareaNormalAppearance
                      } h-3/5 w-full md:h-full md:w-5/6`}
                      placeholder="Working the work…"
                    />
                  </div>
                  <div className="flex flex-row space-x-2 md:flex-col md:space-y-2">
                    {!disabled && updateMode && (
                      <>
                        <TroiButton
                          text={"Save"}
                          testId={`update-${position.id}`}
                          onClick={handleUpdate}
                          color={buttonBlue}
                        />
                        <TroiButton
                          text={"Cancel"}
                          testId={`cancel-${position.id}`}
                          onClick={handleCancel}
                          color={buttonRed}
                        />
                      </>
                    )}
                    {!disabled && addMode && (
                      <TroiButton
                        text={"Save"}
                        testId={"add-" + position.id}
                        onClick={handleAdd}
                        color={buttonBlue}
                      />
                    )}
                  </div>
                </div>
              </div>
            ) : (
              <div data-testid="entry-card-content">
                <b>{values.hours} Hour(s)</b>
                <br />
                <p>{values.description}</p>
                <br />
                <TroiButton
                  text={"Delete"}
                  testId={`delete-${position.id}`}
                  onClick={() => {
                    deleteClicked?.();
                  }}
                  color={buttonRed}
                />
                {!disabled && (
                  <TroiButton
                    text={"Edit"}
                    testId={`edit-${position.id}`}
                    onClick={() => {
                      // openPhases();
                      setUpdateMode(true);
                    }}
                    color={buttonBlue}
                  />
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
