// old/src/routes/projects/index.svelte
<script>
  // @ts-nocheck

  import { goto } from "$app/navigation";
  import { onMount } from "svelte";

  import { user, logout, loggedIn } from "$lib/stores/auth.js";
  import Troi from "$lib/Troi.svelte";

  onMount(() => {
    if (!$loggedIn) {
      goto("/");
    }
  });

  function handleLogout() {
    logout();
    goto("/");
  }
</script>

<div class="rounded-sm bg-white px-2 py-2 shadow-md sm:w-full md:px-8 md:py-6">
  <nav class="border-1 w-full border-b pb-1 text-center md:text-left">
    <div class=" ">
      <div class="flex h-16 justify-between">
        <div class="flex items-center">
          <img
            src="timetracking_blue.svg"
            alt="Track-Your-Time logo"
            class="p-4"
          />
        </div>
        <div class="flex w-full items-center justify-between">
          <div class="text-black">
            <div class="font-bold">Track-Your-Time</div>
            <div class="text-sm">
              Logged in as {$user.name}.
            </div>
          </div>
          <button
            on:click|preventDefault={handleLogout}
            data-test="add-button"
            class="inline-block h-auto rounded bg-blue-600 px-6 py-2.5 text-xs font-medium uppercase leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg"
          >
            Logout
          </button>
        </div>
      </div>
    </div>
  </nav>

  <Troi />
</div>

// app/routes/projects.tsx
import {
  json,
  type LoaderFunctionArgs,
  type MetaFunction,
} from "@remix-run/node";
import { Form, useLoaderData } from "@remix-run/react";
import { login } from "~/cookies.server";

export const meta: MetaFunction = () => {
  return [
    { title: "Remix Application Template" },
    { name: "description", content: "Hello DigitalService!" },
  ];
};

export async function loader({ request }: LoaderFunctionArgs) {
  const cookieHeader = request.headers.get("Cookie");
  const cookie = (await login.parse(cookieHeader)) || {};
  return json({ username: cookie.username });
}

export default function Index() {
  const { username } = useLoaderData<typeof loader>();

  return (
    <main>
      <div className="rounded-sm bg-white px-2 py-2 shadow-md sm:w-full md:px-8 md:py-6">
        <nav className="border-1 w-full border-b pb-1 text-center md:text-left">
          <div className=" ">
            <div className="flex h-16 justify-between">
              <div className="flex items-center">
                <img
                  src="timetracking_blue.svg"
                  alt="Track-Your-Time logo"
                  className="p-4"
                />
              </div>
              <div className="flex w-full items-center justify-between">
                <div className="text-black">
                  <div className="font-bold">Track-Your-Time</div>
                  <div className="text-sm">Logged in as {username}.</div>
                </div>
                <Form method="post" action="/logout">
                  <button
                    type="submit"
                    data-test="add-button"
                    className="inline-block h-auto rounded bg-blue-600 px-6 py-2.5 text-xs font-medium uppercase leading-tight text-white shadow-md transition duration-150 ease-in-out hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg"
                  >
                    Logout
                  </button>
                </Form>
              </div>
            </div>
          </div>
        </nav>
      </div>
    </main>
  );
}
