// app/components/troi.tsx
import { useState } from "react";
import { InfoBanner } from "./InfoBanner";
import { addDaysToDate, getWeekDaysFor } from "~/utils/dateUtils";
import { WeekView } from "./WeekView";
import { TroiTimeEntries } from "./TroiTimeEntries";
import {
  TrackyTask,
  filterPhaseTasks,
  filterRecurringTasks,
} from "~/tasks/TrackyTask";
import type { CalendarEvent } from "troi-library";
import {
  TransformedCalendarEvent,
  transformCalendarEvent,
} from "~/utils/transformCalendarEvents";
import moment from "moment";
import { TimeEntries, TimeEntry } from "~/troi/TimeEntry";
import { CalculationPosition } from "~/troi/CalculationPosition";
import { useFetcher } from "@remix-run/react";
import { LoadingOverlay } from "./LoadingOverlay";

interface Props {
  calculationPositions: CalculationPosition[];
  calendarEvents: CalendarEvent[];
  timeEntries: TimeEntries;
  tasks: TrackyTask[];
}

function findEventsOfDate(
  calendarEvents: TransformedCalendarEvent[],
  date: Date,
) {
  return calendarEvents.filter((calendarEvent) =>
    moment(calendarEvent.date).isSame(date, "day"),
  );
}

function findTimeEntriesOfDate(timeEntries: TimeEntries, date: Date) {
  return Object.values(timeEntries).filter((entry) =>
    moment(entry.date).isSame(date, "day"),
  );
}

function calcHoursOfDate(timeEntries: TimeEntries, date: Date) {
  return findTimeEntriesOfDate(timeEntries, date).reduce(
    (acc, entry) => acc + entry.hours,
    0,
  );
}

export default function Troi(props: Props) {
  const recurringTasks = filterRecurringTasks(props.tasks);
  const phaseTasks = filterPhaseTasks(props.tasks);

  const [selectedDate, setSelectedDate] = useState(() => new Date());
  const selectedWeek = getWeekDaysFor(selectedDate);

  const calendarEvents = props.calendarEvents
    .map((calendarEvent) =>
      transformCalendarEvent(
        calendarEvent,
        addDaysToDate(new Date(), -366),
        addDaysToDate(new Date(), 366),
      ),
    )
    .flat();
  const selectedDayEvents = findEventsOfDate(calendarEvents, selectedDate);
  const timesAndEventsOfSelectedWeek = selectedWeek.map((weekday) => ({
    hours: calcHoursOfDate(props.timeEntries, weekday),
    events: findEventsOfDate(calendarEvents, weekday),
  }));

  const positions = props.calculationPositions;

  const entriesForSelectedDate = findTimeEntriesOfDate(
    props.timeEntries,
    selectedDate,
  );

  const fetcher = useFetcher();

  async function onAddEntryClicked(
    position: CalculationPosition,
    hours: number,
    description: string,
  ) {
    fetcher.submit(
      {
        hours,
        description,
        calculationPositionId: position.id,
        date: moment(selectedDate).format("YYYY-MM-DD"),
      },
      {
        method: "POST",
        action: `/time_entries`,
      },
    );
  }

  async function onUpdateEntryClicked(entry: TimeEntry) {
    fetcher.submit(
      {
        hours: entry.hours,
        description: entry.description,
      },
      {
        method: "PUT",
        action: `/time_entries/${entry.id}`,
      },
    );
  }

  async function onDeleteEntryClicked(entry: TimeEntry) {
    fetcher.submit(
      {},
      {
        method: "DELETE",
        action: `/time_entries/${entry.id}`,
      },
    );
  }

  return (
    <div>
      <section className="p-4">
        <a
          className="angie-link"
          href="https://digitalservicebund.atlassian.net/wiki/spaces/DIGITALSER/pages/359301512/Time+Tracking"
          target="_blank"
        >
          Read about how to track your time in confluence
        </a>
      </section>
      <section className="z-10 w-full bg-white md:sticky md:top-0">
        <WeekView
          timesAndEventsOfSelectedWeek={timesAndEventsOfSelectedWeek}
          selectedDate={selectedDate}
          onSelectDate={setSelectedDate}
        />
      </section>

      {selectedDayEvents?.map((event) => (
        <InfoBanner
          key={`${event.date.getTime()}-${event.type ?? ""}`}
          event={event}
        />
      ))}

      {!selectedDayEvents?.some((event) => event.type == "Holiday") && (
        <TroiTimeEntries
          calculationPositions={positions ?? []}
          recurringTasks={recurringTasks}
          phaseTasks={phaseTasks}
          entries={entriesForSelectedDate}
          deleteEntry={onDeleteEntryClicked}
          updateEntry={onUpdateEntryClicked}
          addEntry={onAddEntryClicked}
          disabled={false}
        />
      )}

      <section className="mt-8 text-xs text-gray-600">
        <p>
          Project not showing up? Make sure it's available in Troi and marked as
          a "favorite".
        </p>
      </section>

      {fetcher.state !== "idle" && <LoadingOverlay message="Please wait..." />}
    </div>
  );
}

// old/src/lib/Troi.svelte
<script>
  // @ts-nocheck

  import { onMount } from "svelte";
  import { troiApi } from "$lib/apis/troiApiService";
  import TroiTimeEntries from "$lib/components/TroiTimeEntries.svelte";
  import WeekView from "$lib/components/WeekView.svelte";
  import LoadingOverlay from "$lib/components/LoadingOverlay.svelte";
  import { getWeekDaysFor } from "$lib/utils/dateUtils";
  import InfoBanner from "$lib/components/InfoBanner.svelte";
  import TroiController from "$lib/troiController";
  import nocodbApi from "./nocodbClient";
  import { CalendarEventType } from "$lib/stores/transformCalendarEvents";

  const troiController = new TroiController();

  let selectedDate = new Date();
  let selectedWeek = getWeekDaysFor(selectedDate);

  let positions = [];
  let timesAndEventsOfSelectedWeek = [];
  let selectedDayEvents = [];
  let entriesForSelectedDate = {};

  let isLoading = true;

  let phaseTasks;
  let recurringTasks;

  async function getDefaultTasks() {
    let tasks = await nocodbApi.dbTableRow.list(
      "v1",
      "ds4g-data",
      "Tracky-Task"
    );
    phaseTasks = tasks.list.filter((keyword) => keyword.type === "PHASE");
    recurringTasks = tasks.list.filter(
      (keyword) => keyword.type === "RECURRING"
    );
  }

  onMount(async () => {
    // make sure $troiApi from store is not used before it is initialized
    if ($troiApi === undefined) return;

    await troiController.init($troiApi, showLoadingSpinner, hideLoadingSpinner);
    positions = troiController.getProjects();
    await updateUI();
    await getDefaultTasks();
    hideLoadingSpinner();
  });

  async function updateUI() {
    entriesForSelectedDate = await troiController.getEntriesFor(selectedDate);
    timesAndEventsOfSelectedWeek =
      troiController.getTimesAndEventsFor(selectedWeek);
    selectedDayEvents = troiController.getEventsFor(selectedDate);
  }

  async function onSelectedDateChangedTo(date) {
    selectedDayEvents = [];
    selectedDate = date;
    selectedWeek = getWeekDaysFor(selectedDate);
    updateUI();
  }

  async function onAddEntryClicked(position, hours, description) {
    showLoadingSpinner();
    await troiController.addEntry(
      selectedDate,
      position,
      hours,
      description,
      updateUI
    );
    hideLoadingSpinner();
  }

  async function onUpdateEntryClicked(position, entry) {
    showLoadingSpinner();
    await troiController.updateEntry(position, entry, updateUI);
    hideLoadingSpinner();
  }

  async function onDeleteEntryClicked(entry, positionId) {
    showLoadingSpinner();
    await troiController.deleteEntry(entry, positionId, updateUI);
    hideLoadingSpinner();
  }

  function showLoadingSpinner() {
    isLoading = true;
  }

  function hideLoadingSpinner() {
    isLoading = false;
  }
</script>

{#if isLoading}
  <LoadingOverlay message={"Please wait..."} />
{/if}
<section class="p-4">
  <a
    class="angie-link"
    href="https://digitalservicebund.atlassian.net/wiki/spaces/DIGITALSER/pages/359301512/Time+Tracking"
    target="_blank">Read about how to track your time in confluence</a
  >
</section>
<section class="z-10 w-full bg-white md:sticky md:top-0">
  <WeekView
    {timesAndEventsOfSelectedWeek}
    selectedDateChanged={onSelectedDateChangedTo}
  />
</section>

{#each selectedDayEvents as event}
  <InfoBanner {event} />
{/each}
<!-- TODO: set disabled correctly-->
{#if !selectedDayEvents.some((event) => event.type == CalendarEventType.Holiday)}
  <TroiTimeEntries
    {positions}
    {recurringTasks}
    {phaseTasks}
    entries={entriesForSelectedDate}
    deleteEntry={onDeleteEntryClicked}
    updateEntry={onUpdateEntryClicked}
    addEntry={onAddEntryClicked}
    disabled={false}
  />
{/if}
<section class="mt-8 text-xs text-gray-600">
  <p>
    Project not showing up? Make sure it's available in Troi and marked as a
    "favorite".
  </p>
</section>

<style>
  :root {
    --date-input-width: 6.5rem;
  }
</style>
